version: '3.8'

services:

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
     - ./frontend:/app:delegated
     - /node_modules
    ports:
      - 3005:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 8000:5000
    networks:
      test:
        ipv4_address: 172.18.0.12
  database:
    container_name: database
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
        #env_file: postgres.env
    volumes:
      - ./data:/var/lib/postgres/data
        # - ./db_files/1-messages.sql:/docker-entrypoint-initdb.d/01-messages.sql
    networks:
      test:
        ipv4_address: 172.18.0.11
networks:
  test:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
